{
 "title": "jwt-pizza-service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "users_active_users{source=\"jwt-pizza-service\", type=\"activity\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(auth_success{source=\"jwt-pizza-service\", type=\"attempt\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(auth_failed{source=\"jwt-pizza-service\", type=\"attempt\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"DELETE\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"GET\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"POST\"}[1m])",
     "legendFormat": "Post"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"PUT\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate(request_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{source=\"jwt-pizza-service\", type=\"memory\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{source=\"jwt-pizza-service\", type=\"cpu\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_ms{source=\"jwt-pizza-service\", type=\"service\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(pizza_total{source=\"jwt-pizza-service\", type=\"sold\"}[1m])",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "pizza_total{source=\"jwt-pizza-service\", type=\"failure\"}",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_total{source=\"jwt-pizza-service\", type=\"revenue\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_ms{source=\"jwt-pizza-service\", type=\"pizza_creation\"}",
     "legendFormat": "Request Latency"
    }
   ]
  }
 ]
}